ALTER TYPE "user_role" ADD VALUE IF NOT EXISTS 'OPERATOR_ADMIN';
ALTER TYPE "user_role" ADD VALUE IF NOT EXISTS 'DRIVER';
ALTER TYPE "user_role" ADD VALUE IF NOT EXISTS 'CONDUCTOR';
ALTER TYPE "bus_status" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';

ALTER TABLE "operators" ADD COLUMN IF NOT EXISTS "corridor" varchar(200) DEFAULT 'State Rural Corridor' NOT NULL;
ALTER TABLE "operator_members" ADD COLUMN IF NOT EXISTS "bus_id" uuid REFERENCES "buses"("id") ON DELETE SET NULL;
ALTER TABLE "operator_members" ADD COLUMN IF NOT EXISTS "created_by" varchar(50) DEFAULT 'OWNER' NOT NULL;
ALTER TABLE "buses" ADD COLUMN IF NOT EXISTS "amenities" jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "buses" ADD COLUMN IF NOT EXISTS "created_by" varchar(50) DEFAULT 'SUPER_ADMIN' NOT NULL;
